// =====================================================================
// MASTER DATA TAMU UNDANGAN KHUSUS: HAUL & HAFLAH P3TQ - MHMTQ
// Sesuai Laporan Blok 3 (§17.1):
// 25 Penguji Al-Qur-an & Huffadh + 45 Asatidz Purna Bakti & Masyaikh
// Total = 70 Tamu Undangan Khusus (140 Kuota Dasar · Tiket Putih VIP)
// =====================================================================

export interface MasterUndangan {
  code: string;
  nama: string;
  kategori: string;
  subKategori: 'PENGUJI' | 'ASATIDZ_MASYAIKH';
  instansi: string;
  kuotaDasar: number;
  warnaTiket: string;
}

export const MASTER_UNDANGAN_LIST: MasterUndangan[] = [
  // --- 25 PENGUJI AL-QUR'AN & HUFFADH (50 KUOTA) ---
  {
    code: 'UND0101',
    nama: 'KH. ABDULLAH FAQIH',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'LPTQ Jawa Timur',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0102',
    nama: 'KH. MUHAIMIN ZEN, M.A.',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'Jam\'iyyatul Qurro\' wal Huffadh PBNU',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0103',
    nama: 'KH. SYU\'AIB MALIK',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'Lajnah Pentashih Al-Qur\'an',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0104',
    nama: 'KH. FATHONI DIMYATI',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'Pondok Yanbu\'ul Qur\'an Kudus',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0105',
    nama: 'KH. DZUL HILMI GHOZALI',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'Masjid Nasional Al-Akbar Surabaya',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0106',
    nama: 'KH. MUDAWI MA\'RUF',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'Kanwil Kemenag Jawa Timur',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0107',
    nama: 'NYAI HJ. NIHAYAH',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'Penguji Huffadh Putri PP. Lirboyo',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0108',
    nama: 'NYAI HJ. FATIMAH AZZAHRA',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'PP. Al-Munawwir Krapyak Yogyakarta',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0109',
    nama: 'KH. AHMAD ROZIQIN',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'LPTQ Kota & Kab. Kediri',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0110',
    nama: 'KH. M. BASORI ALWI',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'PIQ Singosari Malang',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0111',
    nama: 'NYAI HJ. UMI KULSUM',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'PP. Tahfizh Yanbu\' Kudus',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0112',
    nama: 'KH. ABDUL MANAN GHANI',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'Lembaga Dakwah PBNU',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0113',
    nama: 'NYAI HJ. WARDATUL JAMILAH',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'PP. Madrasatul Qur\'an Tebuireng',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0114',
    nama: 'KH. MUNAWWIR AFANDI',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'Jam\'iyyatul Huffadh Tuban',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0115',
    nama: 'KH. ZAINUL ARIFIN',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'LPTQ Kabupaten Blitar',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0116',
    nama: 'KH. ABDUL QODIR JAELANI',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'PP. Al-Huda Tulungagung',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0117',
    nama: 'NYAI HJ. BADRIYAH FAYUMI',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'Pondok Pesantren Babakan Ciwaringin Cirebon',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0118',
    nama: 'KH. HASAN ASY\'ARI',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'Penguji Huffadh Pasuruan',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0119',
    nama: 'KH. SHODIQ HAMZAH',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'PP. Asshodiqiyyah Semarang',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0120',
    nama: 'NYAI HJ. ROMLAH',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'PP. Tahfizh Al-Fattah Nganjuk',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0121',
    nama: 'KH. IMRON ROSYADI',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'LPTQ Bojonegoro',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0122',
    nama: 'KH. MAS\'UD YUNUS',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'LPTQ Mojokerto',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0123',
    nama: 'NYAI HJ. NURUL LAILI',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'PP. Tahfizh Putri Surabaya',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0124',
    nama: 'KH. NURUL HUDA MA\'SHUM',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'PP. Al-Hidayah Lasem',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0125',
    nama: 'KH. AHMAD MUSTAFA BISRI',
    kategori: 'Penguji Al-Qur-an & Huffadh',
    subKategori: 'PENGUJI',
    instansi: 'PP. Raudlatut Thalibin Rembang',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },

  // --- 45 ASATIDZ PURNA BAKTI & MASYAIKH (90 KUOTA) ---
  {
    code: 'UND0126',
    nama: 'KH. M. ANWAR MANSHUR',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Pengasuh Utama PP. Lirboyo Kediri',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0127',
    nama: 'KH. ABDULLOH KAFABIHI MAHRUS',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Pengasuh PP. Lirboyo / Rektor IAIT',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0128',
    nama: 'KH. NURUL HUDA DJAZULI',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Masyayikh PP. Al-Falah Ploso Kediri',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0129',
    nama: 'KH. HASAN SYUKRI ZARKASYI',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Masyayikh Pesantren Ponorogo',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0130',
    nama: 'KH. ATHO\'ILLAH SHOLAHUDDIN ANWAR',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Majelis Masyayikh PP. Lirboyo',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0131',
    nama: 'KH. REZA AHMAD ZAHID, Lc., M.A.',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Masyayikh PP. Lirboyo / IAIT',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0132',
    nama: 'KH. AN\'IM FALAHUDDIN MAHRUS',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Masyayikh PP. Lirboyo Kediri',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0133',
    nama: 'KH. DAHLAN RIDLWAN',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Asatidz Sepuh MHMTQ Lirboyo',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0134',
    nama: 'KH. ANWAR ISKANDAR',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Ketua Umum MUI / PP. Al-Amien Kediri',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0135',
    nama: 'KH. AGOES ALI MASYHURI',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'PP. Bumi Shalawat Sidoarjo',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0136',
    nama: 'KH. MARZUKI MUSTAMAR',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'PP. Sabilurrosyad Gasek Malang',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0137',
    nama: 'KH. SUBHAN MAKMUN',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'PP. Assalafiyah Brebes Jawa Tengah',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0138',
    nama: 'NYAI HJ. AZIMATUL QUDSIYYAH',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Asatidzah Purna Bakti P3TQ Lirboyo',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0139',
    nama: 'NYAI HJ. AZIZAH MA\'SHOEM',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'PP. Al-Hidayat Lasem Rembang',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0140',
    nama: 'NYAI HJ. DURROH NAFISAH',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'PP. Al-Munawwir Krapyak Yogyakarta',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0141',
    nama: 'NYAI HJ. UMI HANIK',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Asatidzah Sepuh P3TQ Lirboyo',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0142',
    nama: 'KH. SYUKRON MA\'MUN',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'PP. Darur Rahman Jakarta',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0143',
    nama: 'KH. MA\'RUF ZAINUDDIN',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Asatidz Sepuh MHM Lirboyo',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0144',
    nama: 'KH. BADRUL HUDA ZAINAL ABIDIN',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'PP. Lirboyo Unit Darussalam',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0145',
    nama: 'KH. HABIBULLOH ZAWAWI',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Masyayikh PP. Lirboyo HM Al-Mahrusiyah',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0146',
    nama: 'KH. AHMAD HASANUDDIN',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Asatidz Purna Bakti MHMTQ',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0147',
    nama: 'KH. IHYA\' ULUMIDDIN',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'PP. Nurul Haromain Pujon Malang',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0148',
    nama: 'KH. SYAFI\'I SULAIMAN',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Asatidz Sepuh Pondok Lirboyo',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0149',
    nama: 'KH. ZUHRUL ANAM HISYAM',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'PP. At-Taujieh Al-Islamy Banyumas',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0150',
    nama: 'NYAI HJ. KHADIJAH MAHRUS',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Keluarga Ndalem Masyayikh Lirboyo',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0151',
    nama: 'KH. MUHYIDDIN KHOTIB',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'PP. Salafiyah Syafi\'iyah Sukorejo Situbondo',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0152',
    nama: 'KH. MUSTOFA AQIEL SIRADJ',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'PP. KHAS Kempek Cirebon',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0153',
    nama: 'KH. ABDUL HADI ASY\'ARI',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Asatidz Purna Bakti Lirboyo',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0154',
    nama: 'NYAI HJ. NUR HANNAH',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Asatidzah Purna Bakti MHMTQ',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0155',
    nama: 'KH. ASYHAR SHOFWAN',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'PP. Darussalam Nganjuk',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0156',
    nama: 'KH. SHOLEH QOSIM',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Tokoh Alumni Sepuh Lirboyo',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0157',
    nama: 'KH. ZAINUDDIN JAZULI',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Masyayikh PP. Al-Falah Ploso',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0158',
    nama: 'KH. CHOLIL NAFIS, Ph.D.',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Ketua MUI Bidang Dakwah',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0159',
    nama: 'KH. ABDUL HANNAN MA\'SHUM',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'PP. Fathul Ulum Kwagean Kediri',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0160',
    nama: 'NYAI HJ. MASRUROH WAHID',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Ketua PW Muslimat NU Jawa Timur',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0161',
    nama: 'KH. ACHMAD CHALWANI NAWAWI',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'PP. An-Nawawi Berjan Purworejo',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0162',
    nama: 'KH. ABDUL MATIN DJAWAHIR',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'PP. Sunan Bejagung Tuban',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0163',
    nama: 'KH. ABDURRAHMAN AL-KAUTSAR (GUS KAUTSAR)',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'PP. Al-Falah Ploso Kediri',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0164',
    nama: 'KH. AHMAD BAHAUDDIN NOOR SALIM (GUS BAHA)',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'PP. LP3IA Narukan Kragan Rembang',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0165',
    nama: 'NYAI HJ. AISYAH AHMAD',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Asatidzah Purna Bakti P3TQ Kediri',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0166',
    nama: 'KH. LUQMAN HAKIM HARITS DIMYATHI',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'PP. Tremas Pacitan Jawa Timur',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0167',
    nama: 'KH. ZAINAL ABIDIN',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Asatidz Purna Bakti MHM Lirboyo',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0168',
    nama: 'KH. MUHIBBUL AMAN ALY',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'PP. Al-Fithrah Kedinding Surabaya',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0169',
    nama: 'NYAI HJ. UMI NASIHAH',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'Asatidzah Sepuh P3TQ Lirboyo',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
  {
    code: 'UND0170',
    nama: 'KH. M. ABDURRAHMAN FAQIH',
    kategori: 'Asatidz Purna Bakti & Masyaikh',
    subKategori: 'ASATIDZ_MASYAIKH',
    instansi: 'PP. Langitan Widang Tuban',
    kuotaDasar: 2,
    warnaTiket: 'Putih VIP',
  },
];
